### ISSUE TITLE
Exception running ArcGISRuntime.WinUI.Viewer:  Unable to load 'Microsoft.ui.xaml.dll' 

### ISSUE THREAD

**Issue by kirkktx** [Esri/arcgis-maps-sdk-dotnet-samples#1105]
Tried upgrading Microsoft.WindowsAppSDK from 1.1.3 to 1.1.5, but still same result

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=ArcGISRuntime.WinUI.Viewer
  StackTrace:
   at ArcGISRuntime.WinUI.Viewer.Program.XamlCheckProcessRequirements()
   at ArcGISRuntime.WinUI.Viewer.Program.Main(String[] args) in C:\Repos\esri\arcgis-runtime-samples-dotnet\src\WinUI\ArcGISRuntime.WinUI.Viewer\obj\x64\Debug\net6.0-windows10.0.19041.0\App.g.i.cs:line 28

**Comment by kirkktx** [comment]
Installed Windows App SDK visual studio extension, still get same exception

**Comment by praveenaak** [comment]
Thanks for reporting this. This issue relates to .NET 6 and Windows App SDK 1.1.x and has had no recent activity. The current WinUI viewer uses .NET 10 and Windows App SDK 1.8 so I’m closing this as outdated. If the problem still occurs with the current viewer, please open a new issue with updated reproduction details.
